### ISSUE TITLE
离线包生产环境使用问题

### ISSUE THREAD

**Issue by xdmaolei** [JDFED/JDHybrid#4]
看了代码以后有以下两个疑问：
1. 在生产环境使用的时候，是以页面维度还是以业务的维度产出离线包？
2. 前端产出离线包的webpack插件代码后续有开源计划么？

**Comment by huangturen** [comment]
> 

1. 当前我们开源的是离线包的拦截机制的代码，这是做离线包的基础，至于要以页面为维度还是业务为维度，您完全可以基于自己的业务现状进行设计。我们自己的离线包既有页面维度的，也有一类业务维度的，这都是完全可以实现的。
2. https://github.com/JDFED/JDHybrid/blob/main/nodejs/README.md 这里其实已经开源了离线包制作的代码了，希望对您有帮助。

**Comment by huangturen** [comment]
close
