### ISSUE TITLE
iOS JDCache中 formdata上传问题疑问

### ISSUE THREAD

**Issue by huainanzi** [JDFED/JDHybrid#5]
![截屏2023-04-13 14 58 25](https://user-images.githubusercontent.com/17873544/231682423-0e3b4ad3-79d1-4f31-8e02-1e41e7c07751.png)
在使用JDCache中，post请求上传blob数据，hook后由native处理，这里的url遇到图中这种需要拼接的时候，代码中是webView.URL.absoluteString去除query,然后拼接上params中传过来的url,我们这里实践发现会多出来webView.URL.absoluteString中的path部分，这里为什么不是webView.URL.absoluteString中的域名直接拼接params中传过来的url
请教下，这里是大佬业务特性还是这里有不足

**Comment by XiaoruiWang-SH** [comment]
这个是我们最初的业务特性保留下来的代码，现在这个逻辑应该不需要了，因为拦截http/https的情况下，传过来的URL不应该不带scheme

**Comment by huainanzi** [comment]
我们实践发现，现在传过来的URL就是不带scheme，这是bug吗或者说不带scheme的url如何拼接处理能通用

**Comment by XiaoruiWang-SH** [comment]
业务应该保证传过来的URL是完整的，不然的话JDCache也无法知道该怎么拼接正确的URL
