### ISSUE TITLE
你好，经测试发现，拦截前后页面的打开时长却别不大。使用的是这种方式: JDCacheH5LoadTypeNativeNetwork

### ISSUE THREAD

**Issue by zwcshy** [JDFED/JDHybrid#6]
有几个问题： 
1. 这种方式在拦截资源，并加载资源成功之后，不会把资源放到本地或者内存中吗？
2. 每次打开H5页面，都走远程，不走本地的逻辑是吗?   
3. This task has already been stopped  会偶尔出现这个崩溃

**Comment by BAOYANGZHOU** [comment]
H5资源请求拦截后走原生对性能的提升主要体现在js、css、image等资源的缓存上。拦截对性能的实际提升用户弱感知。只有当图片资源较大、下载网络耗时较长时，用户才能感知到图片打开速度的提升。
JDCacheH5LoadTypeNativeNetwork 会设置 configuration.loader.enable = YES，loader.enable开启后js、css、image等资源会缓存到disk。
loader.enable开启后，http、https网络请求都会走原生网络通道，异常时会降级到webview进行加载。
